# Generated by Django 3.2.5 on 2022-03-14 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0007_auto_20220314_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ManyToManyField(related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
