# Generated by Django 3.2.5 on 2022-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_ticket_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
